runtime: python37

env_variables:
  SECERT_KEY: "71eb7c87-d957-4882-bb82-27b3b76cf781"
  GDB_USERNAME: "root"
  GDB_PASSWORD: "RMIT1234!!!"
  GDB_HOST: ""
  GDB_DATABASE: "Database"
  GDB_QUERY: "?unix_socket=/cloudsql/budding-investors-248807:australia-southeast1:database"